# -----------------------------------------------------------------------------
# Author: Simone Machetti
# -----------------------------------------------------------------------------

../../rtl/acc_array_bfp.sv
../../rtl/acc_array_bpl_bfp.sv
../../rtl/acc_array_sqr_bfp.sv
../../rtl/acc_array_sqr.sv
../../rtl/acc_array.sv
../../rtl/add_n.sv
../../rtl/align_bfp.sv
../../rtl/align_cell_bfp.sv
../../rtl/booth_r4_cell.sv
../../rtl/booth_r4.sv
../../rtl/comp_n.sv
../../rtl/const_sqr_bfp.sv
../../rtl/const_sqr.sv
../../rtl/cpr_c_n.sv
../../rtl/cpr_w_n.sv
../../rtl/ctrl_sqr.sv
../../rtl/ctrl.sv
../../rtl/disp_array_a_sqr.sv
../../rtl/disp_array_a.sv
../../rtl/disp_array_b_bpl_bfp.sv
../../rtl/disp_array_b_sqr.sv
../../rtl/disp_array_b.sv
../../rtl/disp_array_exp_a_bfp.sv
../../rtl/disp_array_exp_a_sqr_bfp.sv
../../rtl/disp_array_exp_b_bfp.sv
../../rtl/disp_array_exp_b_sqr_bfp.sv
../../rtl/dp_8_alpha_sqr.sv
../../rtl/dp_8_beta_sqr.sv
../../rtl/dp_8_bpl_bfp.sv
../../rtl/dp_8_sqr.sv
../../rtl/dp_8.sv
../../rtl/ext_inject_sqr_bfp.sv
../../rtl/ext_n.sv
../../rtl/fa.sv
../../rtl/gate_a_n_sqr.sv
../../rtl/gate_b_n_bpl_bfp.sv
../../rtl/gate_b_n_sqr.sv
../../rtl/gate_b_n.sv
../../rtl/gate_n_beta_sqr.sv
../../rtl/gate_n_sqr.sv
../../rtl/gate_n.sv
../../rtl/icg.sv
../../rtl/mux_n.sv
../../rtl/pe_array_alpha_sqr_bfp.sv
../../rtl/pe_array_alpha_sqr.sv
../../rtl/pe_array_beta_sqr_bfp.sv
../../rtl/pe_array_beta_sqr.sv
../../rtl/pe_array_bfp.sv
../../rtl/pe_array_bpl_bfp.sv
../../rtl/pe_array_sqr_bfp.sv
../../rtl/pe_array_sqr.sv
../../rtl/pe_array.sv
../../rtl/pe_bfp.sv
../../rtl/pe_bpl_bfp.sv
../../rtl/pe_sqr_bfp.sv
../../rtl/pe_sqr.sv
../../rtl/pe.sv
../../rtl/reg_n.sv
../../rtl/s_5_bit_sqr.sv
../../rtl/shift_n_bfp.sv
../../rtl/shift_n.sv
../../rtl/sub_n_bfp.sv
../../rtl/top_dummy.sv
../../rtl/top_NxN_bfp.sv
../../rtl/top_NxN_bpl_bfp.sv
../../rtl/top_NxN_sqr_bfp.sv
../../rtl/top_NxN_sqr.sv
../../rtl/top_NxN.sv
